
  # For modes: STANDARD, AUTH
  adempiere.processor:
    image: ${ADEMPIERE_PROCESSOR_IMAGE}
    container_name: ${ADEMPIERE_PROCESSOR_CONTAINER_NAME}
    hostname: ${ADEMPIERE_PROCESSOR_HOSTNAME}
    depends_on:
      postgresql.service:
        condition: service_healthy
    restart: ${GENERIC_RESTART}
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/50059; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      DB_HOST: ${ADEMPIERE_PROCESSOR_DB_CONTAINER_NAME}
      DB_PORT: ${ADEMPIERE_PROCESSOR_DB_PORT}
      DB_NAME: ${ADEMPIERE_PROCESSOR_DB_NAME}
      DB_USER: ${ADEMPIERE_PROCESSOR_DB_USER}
      DB_PASSWORD: ${ADEMPIERE_PROCESSOR_DB_PASSWORD}
      SERVER_PORT: ${ADEMPIERE_PROCESSOR_PORT}
    volumes:
      - ${TIMEZONE_PATH_ON_HOST}:${TIMEZONE_PATH_ON_CONTAINER}:${TIMEZONE_OPTIONS}    # Map the Timezone  of the host to the Timezone of the container
      - ${LOCALTIME_PATH_ON_HOST}:${LOCALTIME_PATH_ON_CONTAINER}:${LOCALTIME_OPTIONS} # Map the Localtime of the host to the Timezone of the container
    networks:
      - adempiere_network
