
  # For modes: STORAGE
  grpc.proxy:
    image: ${ENVOY_GRPC_PROXY_BACKEND_IMAGE}
    container_name: ${ENVOY_GRPC_PROXY_CONTAINER_NAME}
    hostname: ${ENVOY_GRPC_PROXY_HOSTNAME}
    depends_on:
      adempiere.grpc.server:
        condition: service_healthy
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/${ENVOY_GRPC_PROXY_BACKEND_PORT}; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      SERVER_PORT: ${ENVOY_GRPC_PROXY_BACKEND_PORT}
      BACKEND_HOST: ${ENVOY_GRPC_PROXY_BACKEND_HOST}
      BACKEND_PORT: ${ENVOY_GRPC_PROXY_BACKEND_SERVER_PORT}
    # ports:
    #  - ${ENVOY_GRPC_PROXY_BACKEND_EXTERNAL_PORT}:${ENVOY_GRPC_PROXY_BACKEND_PORT}
    volumes:
      - ${TIMEZONE_PATH_ON_HOST}:${TIMEZONE_PATH_ON_CONTAINER}:${TIMEZONE_OPTIONS}    # Map the Timezone  of the host to the Timezone of the container
      - ${LOCALTIME_PATH_ON_HOST}:${LOCALTIME_PATH_ON_CONTAINER}:${LOCALTIME_OPTIONS} # Map the Localtime of the host to the Timezone of the container
    networks:
      - adempiere_network
